orbs:
  node: circleci/node@2.0.1
version: 2.1
workflows:
  test:
    jobs:
      - test
jobs:
  test:
    executor:
      name: node/default
      tag: 13
    steps:
      - checkout
      - npm ci
      - npm test
